### ISSUE TITLE
charmcraft pack on Ubuntu 23.04 (Lunar) fails.

### ISSUE THREAD

**Issue by freyes** [canonical/charmcraft#1104]
When trying to build a charm using ubuntu-23.04 as the base for the build-on and run-on stanzas, I get no charm when using charmcraft-2.2:

```
$ charmcraft pack 
No suitable 'build-on' environment found in 'bases[1]' configuration.                                                                                                                                       
No suitable 'build-on' environment found in 'bases[2]' configuration.                                                                                                                                       
No suitable 'build-on' environment found in 'bases[3]' configuration.                                                                                                                                       
No suitable 'build-on' environment found in 'bases[4]' configuration.                                                                                                                                       
No suitable 'build-on' environment found in 'bases[5]' configuration.                                                                                                                                       
No suitable 'build-on' environment found in 'bases[6]' configuration.                                                                                                                                       
No suitable 'build-on' environment found in 'bases[7]' configuration.                                                                                                                                       
Packing the charm                                                                                                                                                                                           
Building charm in '/root' | (3.0s)                                                                                                                                                                          found charm-tools 3.0.6 (+git-0-1847cbe)
Created 'ovn-dedicated-chassis_ubuntu-22.04-amd64_ubuntu-22.10-amd64.charm'.                                                                                                                                
Charms packed:                                                                                                                                                                                              
    ovn-dedicated-chassis_ubuntu-22.04-amd64_ubuntu-22.10-amd64.charm                
```

Although if I switch to the `latest/edge` channel, I get the following error:

```
Created 'ovn-dedicated-chassis_ubuntu-22.04-amd64_ubuntu-22.10-amd64.charm'.                                                                                                                                
charmcraft internal error: LXDUnstableImageError(brief="Cannot launch an unstable image 'lunar' from remote 'ubuntu-daily'", details='Devel or daily images are not guaranteed and are intended for experimental use only.', resolution=None)
```

The charmcraft.yaml used is the one below. In general we need to be able to build and run charms on any ubuntu base, since Charmed OpenStack is capable of running on LTS releases and interim releases.

Test Case:

```
git clone https://opendev.org/x/charm-ovn-dedicated-chassis
cd charm-ovn-dedicated-chassis/
git fetch https://review.opendev.org/x/charm-ovn-dedicated-chassis refs/changes/38/883438/1 && git checkout FETCH_HEAD
tox -e build
```

Expected Result: charmcraft produces 2 charm files, one for 22.04 and 22.10, another one for 23.04.

Actual Result: only one charm file is built for 22.04 and 22.10

```yaml
type: charm

parts:
  charm:
    source: src/
    plugin: reactive
    reactive-charm-build-arguments:
      - --binary-wheels-from-source
      - -v
    build-packages:
      - git
      - python3-dev
      - libffi-dev
      - libssl-dev
      - rustc
      - cargo
    build-snaps:
      - charm
    build-environment:
      - CHARM_INTERFACES_DIR: $CRAFT_PROJECT_DIR/interfaces/
      - CHARM_LAYERS_DIR: $CRAFT_PROJECT_DIR/layers/
      - MAKEFLAGS: -j$(nproc)

bases:
  - build-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [amd64]
    run-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [amd64]
      - name: ubuntu
        channel: "22.10"
        architectures: [amd64]
  - build-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [arm64]
    run-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [arm64]
      - name: ubuntu
        channel: "22.10"
        architectures: [arm64]
  - build-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [ppc64el]
    run-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [ppc64el]
      - name: ubuntu
        channel: "22.10"
        architectures: [ppc64el]
  - build-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [s390x]
    run-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [s390x]
      - name: ubuntu
        channel: "22.10"
        architectures: [s390x]
  - build-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [amd64]
    run-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [amd64]
  - build-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [arm64]
    run-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [arm64]
  - build-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [ppc64el]
    run-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [ppc64el]
  - build-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [s390x]
    run-on:
      - name: ubuntu
        channel: "23.04"
        architectures: [s390x]
```
