### ISSUE TITLE
Can't build charm targeted at the current development release: `Skipping 'bases[8].build-on[0]': channel 'devel' does not match host '23.10'.`

### ISSUE THREAD

**Issue by fnordahl** [canonical/charmcraft#1267]
### Bug Description

Slightly, but not quite, related to #1104 and #1203.

As proponents and developers of model driven operations, trying to release machine charms for new versions of, ehh, machines, it would be great to be able to know ahead of time whether your charmed machine operator would work with the next Ubuntu release.

The references above and this bug report serves as proof that this is not currently possible.

### To Reproduce

Attempt to pack a charm with a bases config like:
```yaml
  - build-on:
      - name: ubuntu
        channel: devel
        architectures: [amd64]
    run-on:
      - name: ubuntu
        channel: "23.10"
        architectures: [amd64]
```

### Environment

N/A

### charmcraft.yaml

```shell
N/A
```

### Relevant log output

```shell
See above.
```
