### ISSUE TITLE
Implement platforms for charmcraft

### ISSUE THREAD

**Issue by lengau** [canonical/charmcraft#1535]
### What needs to get done

Follow the specification in ST105. E.g.:

```
base:
    name: ubuntu
    channel: 20.04
platforms:
    ubuntu-amd64:
        build-on: [amd64]
        build-for: [amd64]
```

### Why it needs to get done

Unifying craft products platforms
