### ISSUE TITLE
Charmcraft 3.0.0 renders .charm files missing dispatch script and any meaningful python

### ISSUE THREAD

**Issue by phvalguima** [canonical/charmcraft#1609]
### Bug Description

Hi team,

I am currently running on charmcraft v3.0.0 and I noticed that a charm built with it is getting errors when deploying as such:
```
ERROR invalid charm "sysbench-operator": has no hooks nor dispatch file
```

My code repo: https://github.com/canonical/sysbench-operator

However, a run on my CI using charmcraft v2.5.5 works fine: https://github.com/canonical/sysbench-operator/actions/runs/8292552070/job/22694061013?pr=4

The contents of the final `.charm` are:
```
drwxrwxr-x  3 pguimaraes pguimaraes  4096 Mär 15 11:08 ./
drwxrwxrwt 27 root       root       12288 Mär 15 11:08 ../
-rw-r--r--  1 pguimaraes pguimaraes   249 Mär 15 11:07 manifest.yaml
-rw-r--r--  1 pguimaraes pguimaraes   615 Mär 15 11:04 metadata.yaml
drwxrwxr-x  2 pguimaraes pguimaraes  4096 Mär 15 11:08 scripts/
-rw-r--r--  1 pguimaraes pguimaraes 18019 Mär 15 11:08 sysbench-operator_ubuntu-22.04-amd64.zip
```

snap info charmcraft in my env: https://pastebin.canonical.com/p/w7pY7QJkWZ/
Full `charmcraft pack --debug -v` logs: https://pastebin.canonical.com/p/WSHg2Yxfwp/

### To Reproduce

Install charmcraft v3.0.0 
Checkout the repo above

Copy this: https://pastebin.canonical.com/p/3qsZ5dQd66/ to `requirements.txt`

 try build and deploy the repo above with `charmcraft pack`

### Environment

Ubuntu 23.10

### charmcraft.yaml

```shell
type: charm
bases:
  - build-on:
    - name: ubuntu
      channel: "22.04"
    run-on:
    - name: ubuntu
      channel: "22.04"
parts:
  charm:
    override-pull: |
      craftctl default
      if [[ ! -f requirements.txt ]]
      then
          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
          exit 1
      fi
    charm-strict-dependencies: true
    prime:
      - scripts
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - rustc
      - cargo
```
```


### Relevant log output

```shell
See the bug report pastebins
```

**Comment by lengau** [comment]
Hi, and thanks for the report. This is an intentional, but unfortunate breaking change in 3.0. We've [added some documentation about it](https://juju.is/docs/sdk/include-extra-files-in-a-charm)

The reason for the change is to match the behaviour of the `prime` keyword in apps like snapcraft and rockcraft - `prime` is not supposed to add additional files, but rather to limit what you're using.

Changing your `parts` section roughly as follows should generate a valid charm:

```yaml
parts:
  charm:
    override-pull: |
      craftctl default
      if [[ ! -f requirements.txt ]]
      then
          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
          exit 1
      fi
    charm-strict-dependencies: true
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - rustc
      - cargo
  scripts:
    plugin: dump
    source: .
    prime:
      - scripts
```
