### ISSUE TITLE
Unable to build multi-base subordinate charms on 24.04

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/charmcraft#1789]
### Bug Description

Subordinate charms use the base of the principal charm. Therefore, subordinate charms such as MySQL Router need to support multiple bases, since we can't enforce the principal charm to use a particular base. Currently MySQL Router supports 20.04 and 22.04 and plans to support 24.04.

However, with the new `base` and `platforms` syntax in charmcraft 3, it is not possible to build a subordinate charm on 20.04, 22.04, and 24.04 with a single charmcraft.yaml and git branch

Additional context:
I believe @jnsgruk and @sergiusens were/are discussing this. Created an issue to track officially per @taurus-forever's request

### To Reproduce

1. Create charmcraft.yaml with
```yaml
bases:
  - name: ubuntu
    channel: "20.04"
    architectures: [amd64]
  - name: ubuntu
    channel: "22.04"
    architectures: [amd64]
  - name: ubuntu
    channel: "22.04"
    architectures: [arm64]
  - name: ubuntu
    channel: "24.04"
    architectures: [amd64]
  - name: ubuntu
    channel: "24.04"
    architectures: [arm64]
```
2. charmcraft pack

### Environment

Ubuntu 22.04

### charmcraft.yaml

```shell
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

type: charm
bases:
  # Whenever "bases" is changed:
  # - Update tests/conftest.py::pytest_configure()
  # - Update .github/workflow/ci.yaml integration-test matrix
  - name: ubuntu
    channel: "20.04"
    architectures: [amd64]
  - name: ubuntu
    channel: "22.04"
    architectures: [amd64]
  - name: ubuntu
    channel: "22.04"
    architectures: [arm64]
  - name: ubuntu
    channel: "24.04"
    architectures: [amd64]
  - name: ubuntu
    channel: "24.04"
    architectures: [arm64]
parts:
  charm:
    override-pull: |
      craftctl default
      if [[ ! -f requirements.txt ]]
      then
          echo 'ERROR: Use "tox run -e build-dev" instead of calling "charmcraft pack" directly' >&2
          exit 1
      fi
    # TODO: enable after https://github.com/canonical/charmcraft/issues/1456 fixed
    charm-strict-dependencies: false
    charm-entrypoint: src/machine_charm.py
    prime:
      - charm_version
      - workload_version
    build-packages:
      - libffi-dev
      - libssl-dev
      - pkg-config
      - rustc
      - cargo
```

### Relevant log output

```shell
Bad charmcraft.yaml content:
- base requires 'platforms' definition: {'name': 'ubuntu', 'channel': '24.04', 'architectures': ['amd64']} (in field 'bases[3]')
- base requires 'platforms' definition: {'name': 'ubuntu', 'channel': '24.04', 'architectures': ['arm64']} (in field 'bases[4]')
```

**Comment by jnsgruk** [comment]
Yes, I have discussed this with Sergio, and briefly with Gustavo. The current design isn't set in stone, and Sergio is going to have a bit of a think about what alternatives may look like.

For the sake of transparency, one area that could be quite problematic for "multi-base" charms is where many Python libraries have transitioned to building certain parts of their CPython code with Rust - this is increasingly popular (`pydantic`, `cryptography`, etc.).

The issue is not that the code is built in Rust, but rather that more and more core Python libraries are including dynamically-linked object files, where we could see incompatibilities across LTS versions of Ubuntu.

The current design indeed means that you must have one `charmcraft.yaml` per base, which is actually consistent with how `snapcraft.yaml` and `rockcraft.yaml` work. It also means that the base can become the definition of when breaking changes are permitted in the DSL, rather than just the version of Charmcraft itself - i.e. we could commit to no more breaking changes in the DSL for `charmcraft.yaml` until `ubuntu@26.04` is used.

I definitely think we should investigate this, even if we do in fact end up with one artefact per base, we might be able to ease the developer experience slightly - and perhaps even introduce a `bare` base where there is no CPython code present and the subordinate is all just "plain python" that's LTS-agnostic.

**Comment by jnsgruk** [comment]
For the reader, the proposed new syntax is:

```yaml
name: some-charm
type: charm

# Here is the biggest difference - a single base per charmcraft.yaml
base: ubuntu@22.04

platforms:
  amd64:
  arm64:
  armhf:

# ...
```

**Comment by dragomirp** [comment]
Python requirements are specified outside of `charmcraft.yaml` (in `requirements.txt`), so dealing with dependency incompatibilities between bases will have to be handled elsewhere either way. IMHO removing multiple bases will not help with managing those, but will add another moving part to deal with when trying to support multiple bases.

**Comment by jnsgruk** [comment]
> But I think we might be talking about incompatibilities of wheels/virtual environments across bases—e.g. a pyyaml wheel built on ubuntu 20.04 (python 3.8) will not work on 22.04 (python 3.10). By building on the same base that we run on (with charmcraft), we are no longer concerned about these incompatibilities

Yes, indeed - that is what I'm referring to here 🙂

**Comment by ca-scribner** [comment]
What are we doing to prevent code duplication with this change?  The naive next step for charmers will be keeping one branch or charm directory per base (since charmcraft doesn't cater to multiple charmcraft files in one dir).  That's a lot of code duplication we're forcing them to handle.  The issue is a bit worse for libraries too, where its unclear which instance of the code owns the library.

If we're requiring a different charmcraft.yaml per base, charmcraft should make that easy to administer.

**Comment by jnsgruk** [comment]
That's precisely the problem I'm working to solve with @sergiusens and @niemeyer - though we've not yet reached any conclusion. To be continued :)

**Comment by hloeung** [comment]
With having a different `charmcraft.yaml` per base, how does one tell `charmcraft pack` to use a specific `charmcraft.yaml`?

**Comment by ca-scribner** [comment]
Is there any update on this issue?

**Comment by simskij** [comment]
For anyone who, like me, did not feel that it was clear how to use these new constructs, see [the following article](https://snapcraft.io/docs/reference-architectures) in the snapcraft docs.

**Comment by Maharacha** [comment]
With these new things using platforms etc. in charmcraft.yaml, how do I do this?
```
bases:
  - build-on:
      - name: ubuntu
        channel: "20.04"
    run-on:
      - name: ubuntu
        channel: "20.04"
        architectures: [amd64]
  - build-on:
      - name: ubuntu
        channel: "22.04"
    run-on:
      - name: ubuntu
        channel: "22.04"
        architectures: [amd64]
```
