### ISSUE TITLE
approach for using store commands programmatically 

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/charmcraft#183]
Hello,

We are trying to create some release infrastructure to help us automate releasing charms to the store. Is anyone currently using store commands  programmatically? It seems we currently need to auth against the ubuntu one from the browser. Is there a way to do this without a human?

Thanks

**Comment by jamesbeedy** [comment]
We have had a good experience publishing to the snap store using the snapcraft action.
```
      - name: "Install Snapcraft"
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: "Push snap to snapstore edge"
        run: |
          snapcraft push ${{needs.build-snap.outputs.snap_file}} --release edge
```
Possibly charmcraft can do something similar?
