### ISSUE TITLE
Pep 518 support for charm metadata

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#19]
Related to #18. Would it be possible to support defining charm metadata in `pyproject.toml` as specified in pep 518?

https://www.python.org/dev/peps/pep-0518/#tool-table

As an example of what I mean, it would be nice to be able to specify my charm's metadata like this in `pyproject.toml`:

```toml
[tool.charmcraft.metadata]
name = "charm-name"
display-name = "Charm Name"
summary = "Charm summary"
description = "Charm description"
repo = "https://github.com/repo/name"
license = "GPLv2"
maintainers = [
  "Full Name <full@name.com>",
]
tags = [
  "tag1",
  "tag2",
]
series = [
  "kubernetes",
]

[tool.charmtools.config.example-option]
type = "string"
default = "example"
description = "example description
```

This would have a few advantages:
 - Unifies all of the old yaml configuration files (config.yaml, layer.yaml, metadata.yaml) as well as dependency management into a single file
 - Integrates well into the rest of the Python ecosystem by using an already defined and official standard
 - TOML is simpler and has fewer edge cases than YAML
