### ISSUE TITLE
Cannot stage packages with charmcraft

### ISSUE THREAD

**Issue by yanksyoon** [canonical/charmcraft#1990]
### Bug Description

A simple charmcraft yaml w/ stage packages breaks with error: `Unknown error: E:The method driver /snap/charmcraft/4914/usr/lib/apt/methods/http could not be found.`.

```
name: test
type: charm
title: test charm
summary: test summary
description: test description
base: ubuntu@24.04
parts:
  charm:
    plugin: nil
    stage-packages:
    - wget
platforms:
  amd64:
```

### To Reproduce

use the charmcraft.yaml above and run `charmcraft pack`

### Environment

$ charmcraft --version
charmcraft 3.2.1

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy

### charmcraft.yaml

```yaml
name: test
type: charm
title: test charm
summary: test summary
description: test description
base: ubuntu@24.04
parts:
  charm:
    plugin: nil
    stage-packages:
    - wget
platforms:
  amd64:
```

### Relevant log output

```shell
Unknown error: E:The method driver /snap/charmcraft/4914/usr/lib/apt/methods/http could not be found.                                                                                                                     
Failed to execute charmcraft in instance.                                                                                                                                                                                 
```
```
