### ISSUE TITLE
Support pep 517 for building charms

### ISSUE THREAD

**Issue by knkski** [canonical/charmcraft#20]
[Pep 517](https://www.python.org/dev/peps/pep-0517/) defines a key in `pyproject.toml` that allows a developer to specify how a Python project is built. Would it be possible to support that standard with charmcraft? As an example, this could be what a charm author puts into `pyproject.toml`:

```toml
[build-system]
requires = ["charmcraft", "wheel"]
build-backend = "charmcraft"
```

This would allow frictionless integration with commands such as `pip wheel`.
