### ISSUE TITLE
charmcraft.yaml validation errors are not helpful

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charmcraft#2071]
### Bug Description

it'd be good to know what is invalid about a yaml file if validation fails.

### To Reproduce

charmcraft pack

### Environment

charmcraft 3.2.2

### charmcraft.yaml

```yaml
# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.
name: database
display-name: KeyDB
description: Simple KeyDB charm for Kubernetes.
summary: Troublemaker charm.
maintainers:
  - Pietro Pasotti <pietro.pasotti@canonical.com>

assumes:
  - juju >= 3.6.0
  - k8s-api

type: charm

bases:
  - build-on:
      - name: "ubuntu"
        channel: "20.04"
    run-on:
      - name: "ubuntu"
        channel: "20.04"

containers:
  keydb:
    resource: keydb-image

resources:
  keydb-image:
    type: oci-image
    description: Ubuntu LTS Docker image for KeyDB
    # Included for simplicity in integration tests
    upstream-source: eqalpha/keydb

provides:
  db:
    interface: db

config:
  options:
    requirepass:
      default:
      description: password to require
      type: string
    port:
      default: 6379
      type: int
    appendonly:
      default: 'no'
      type: string
```


### Relevant log output

```shell
❯ charmcraft pack                                                                                                                                                                                                                                                                                                                          
Invalid file: 'metadata.yaml'                                                                                                                                                                                                                                                                                                                  
Recommended resolution: Ensure metadata.yaml meets the juju metadata.yaml specification.                                                                                                                                                                                                                                                       
For more information, check out: https://juju.is/docs/sdk/metadata-yaml                                                                                                                                                                                                                                                                        
Full execution log: '/home/pietro/.local/state/charmcraft/log/charmcraft-20250110-134846.839621.log'
```
