### ISSUE TITLE
charmcraft pack outputs different charm filenames depending on base/platform specification in charmcraft.yaml

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charmcraft#2174]
### Bug Description

depending on whether you use the `base:` or the `platforms:` syntax in charmcraft.yaml, charmcraft will either create a `foo-ubuntu@22.04.charm`, or a `foo-ubuntu-22.04.charm` file.

I believe the created files should have the same name regardless of the syntax that was used to specify them.

### To Reproduce

charmcraft pack in `https://github.com/canonical/parca-scrape-target-operator` 
charmcraft pack in `https://github.com/canonical/parca-k8s-operator` 

### Environment

candidate snap

### charmcraft.yaml

```yaml
n/a
```

### Relevant log output

```shell
n/a
```

**Comment by lengau** [comment]
Hi Pietro! Could you give me an example of the exact `bases` and `platforms` entries where this occurs? This is probably a side-effect of the multi-base platforms work (in which case the naming on the `platforms` syntax probably changed between 3.2 and 3.3).

**Comment by lengau** [comment]
FWIW, when using the `platforms` syntax, Charmcraft *should* add exactly the platform name to your filename, so if you set the platform name to `ubuntu-22.04` it should output `foo-ubuuntu-22.04.charm`, whereas if you set it to `ubuntu@22.04` it should output `foo-ubuntu@22.04.charm`. This *might* be an issue with the multi-base platforms work if we're requiring the platforms to have specific names.

**Comment by PietroPasotti** [comment]
```
bases:
  - build-on:
      - name: "ubuntu"
        channel: "22.04"
    run-on:
      - name: "ubuntu"
        channel: "22.04"
```
vs

```
platforms:
  ubuntu@24.04:amd64:
  ubuntu@22.04:amd64:
```

**Comment by lengau** [comment]
I think this might be working as intended. We don't want to change the bases -> platforms conversion because that's intentionally kept the same from charmcraft 2.x, but the following `platforms` entry should provide the same output:

```yaml
platforms:
  ubuntu-24.04-amd64:
    build-on: [ubuntu@24.04:amd64]
    build-for: [ubuntu@24.04:amd64]
  ubuntu-22.04-amd64:
    build-on: [ubuntu@22.04:amd64]
    build-for: [ubuntu@22.04:amd64]
```

Not sure if the current implementation accepts that input though. If it doesn't, it probably should.

**Comment by PietroPasotti** [comment]
What do you mean with "it might be working as intended"? 
Are you saying that my choice of one of N equivalent ways of declaring metadata are _meant to_ determine the name of the output package?

**Comment by lengau** [comment]
Yes, because the "old" way (`bases`) is deprecated but inherited for historical reasons, and the "new" way is to define the filename based on the platform name string that a user provides, making it user configurable. If you want the platform section of the filename, you can adjust the name of the platform under the `platforms` entry. So something like:

```yaml
name: charmy-mccharmface
platforms:
  my-laptop:
    build-on: [ubuntu@24.04:amd64]
    build-for: [ubuntu@24.04:amd64]
```

would result in a charm named `charmy-mccharmface-my-laptop.charm`
