### ISSUE TITLE
Schema doesn't offer the bundle type

### ISSUE THREAD

**Issue by bepri** [canonical/charmcraft#2192]
### Bug Description

The JSON schema for charmcraft.yaml files _accepts_ defining a bundle charm, but it won't indicate to you that it's an option. It only suggests the "charm" type.

### To Reproduce

Run `charmcraft init`. Then, replace the `type` key's value with something that doesn't exist, like `msi`, and check the validator error from your IDE.

### Environment

Any

### charmcraft.yaml

```yaml
name: epic-charm
type: msi
title: Charm Template
summary: A very short one-line summary of the charm.
description: |
  I'm a short description.

platforms:
  amd64:

parts:
  my-part:
    plugin: nil
```

### Relevant log output

```shell
Value is not accepted. Valid values: "charm".
```
