### ISSUE TITLE
Allow users to specify custom KNOWN_GOOD_PIP_URL for air-gapped CI/CD pipelines

### ISSUE THREAD

**Issue by TresSims** [canonical/charmcraft#2225]
### What needs to get done

Modify the Charmcraft build process to introduce a new flag (e.g., --pip-url) that allows users to specify a custom URL for retrieving pip instead of relying on the hardcoded PythonHosted.com link. This will enable users to utilize locally cached or managed package repositories, improving flexibility and reducing external dependencies.

### Why it needs to get done

In some secure environments it is preferable to use locally cached packages for enhanced security. Without the ability to point the build process to locally cached versions of required dependencies, it is not possible to implement DevOps workflows for charm development.

**Comment by lengau** [comment]
Hi,

This is unlikely to happen any time soon, but you can work around it by replacing the pip wheel in a separate part in your charmcraft.yaml, like so:

```yaml
parts:
  update-pip:
    plugin: nil
    override-pull: |
      rm /usr/share/python-wheels/pip-20.0.2-py2.py3-none-any.whl
      curl -o /usr/share/python-wheels/pip-<something>.whl <wheel-url>
  charm:
    plugin: charm
    after: [update-pip]
    ...
```

This will modify the build environment to get your newer pip from whichever URL you need.
