### ISSUE TITLE
Specify discourage paths for mount points

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#2304]
### Request type

Enhancement

### What needs to get done

It would be handy if we provided some additional insight about storage locations, specifically discouraging some location.

```yaml
storage:
  # ...
  # (Optional) The mount location for filesystem stores. For multi-stores
  # the location acts as the parent directory for each mounted store.
  location: <location>
```

For example, we could say

> Do not use `/charm` or `/tmp` for the location.

### Documentation location

https://canonical-charmcraft.readthedocs-hosted.com/en/stable/reference/files/charmcraft-yaml-file/#storage
