### ISSUE TITLE
charmcraft init uses old style for bases.

### ISSUE THREAD

**Issue by j5awry** [canonical/charmcraft#2340]
### Bug Description

charmcraft  :  3.4.6 : 6672 : latest/stable : canonical✓ : classic

When running `charmcraft init --profile machine` in an empty directory, the resultant `charmcraft.yaml` uses the old style of bases:

```
# (Required for 'charm' type)
bases:
  - build-on:
    - name: ubuntu
      channel: "22.04"
    run-on:
    - name: ubuntu
      channel: "22.04"
```

documentation states that this is the pre-3.0 style : https://canonical-charmcraft.readthedocs-hosted.com/stable/howto/manage-charms/#require-a-specific-base-and-platforms

# Reproducer

in an empty directory, run

`charmcraft init --profile machine`

#  Expectation
A single `base` stanza

```
#(Required for 'charm' type)
base: ubuntu@22.04
```

### To Reproduce

in an empty directory, run

`charmcraft init --profile machine`

### Environment

host: ubuntu 24.04
charmcraft: latest/stable snap

### charmcraft.yaml

```yaml
NOTE: this is essentially the output of charmcraft init, with only title, summary, and description changed.

# This file configures Charmcraft.
# See https://juju.is/docs/sdk/charmcraft-config for guidance.

# (Required)
name: ubuntu-sponsoring-charm


# (Required)
type: charm


# (Recommended)
title: Ubuntu Sponsoring website charm.


# (Required)
summary: Ubuntu Sponsoring website charm.


# (Required)
description: |
  Charm of the Ubuntu Sponsoring website.


# (Required for 'charm' type)
bases:
  - build-on:
    - name: ubuntu
      channel: "22.04"
    run-on:
    - name: ubuntu
      channel: "22.04"


# (Optional) Configuration options for the charm
# This config section defines charm config options, and populates the Configure
# tab on Charmhub.
# More information on this section at https://juju.is/docs/sdk/charmcraft-yaml#heading--config
# General configuration documentation: https://juju.is/docs/sdk/config
config:
  options:
    # An example config option to customise the log level of the workload
    log-level:
      description: |
        Configures the log level of gunicorn.

        Acceptable values are: "info", "debug", "warning", "error" and "critical"
      default: "info"
      type: string
```

### Relevant log output

```shell
None
```
