### ISSUE TITLE
Allow pre-building verifications

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#347]
Charmcraft should allow developers to set up pre-build verifications of their projects.

This could be something very simple like a `flake8 src/charm.py` or more complex like `make tests`. In any case, it's up to the developer, but charmcraft should allow this.

We could add a key in `charmcraft.yaml` that holds what to be executed; if this ends with returncode in 0, charmcraft would procede to the building, else would abort.

Example:

```
pre-build: flake8 mycharm
```

**Comment by sergiusens** [comment]
This could be an option once charmcraftctl is there.

```yaml
parts:
    charm:
        override-pull: |
             charmcraftctl pull
             flake8 mycharm
```
