### ISSUE TITLE
How to pack for CentOS?

### ISSUE THREAD

**Issue by heitorPB** [canonical/charmcraft#356]
After running `charmcraft pack`, i see the `manifest.yaml` contains only references to Ubuntu:

```
bases:
- architectures:
  - amd64
  channel: '20.04'
  name: ubuntu
charmcraft-started-at: '2021-05-26T20:28:53.344575Z'
charmcraft-version: 1.0.0
```

Do the entries in the `metadata.yaml` even matter anymore?

I'm running charmcraft from latest/stable (1.0.0)
