### ISSUE TITLE
We need to support config files

### ISSUE THREAD

**Issue by facundobatista** [canonical/charmcraft#5]
**Multilayer**: we will merge multiple configuration files, in this order (the latter prevails): 
- system: `/etc/charmcraft.yaml`
- user: `($XDG_CONFIG_DIR)/charmcraft.yaml`
- local dir: `charmcraft.yaml` and `.charmcraft.yaml`
- command-line received options

**Discoverable**: the same parameters used in command line (shown with `--help` from the tool) can be applied in the config files. In this POV, the config file is just "a way to avoid needing to pass the same option through the command line"

**Format and structure**: We'll use a YAML file. Internally, it will be separated by commands (as different commands may have equally named option names). General options can be used in the generic `charmcraft` section, but also overriden in the commands. A example valid YAML:

```
charmcraft:
    verbose: true

build:
    requirements:
        - reqs-legacy.txt
        - reqs-new.txt

deploy:
    verbose: 0
```

**Explicitness**: We'll log in debug which files were found and processed, and the final loaded configuration (after merging all those files and given command line modifiers).

**Some details about options types:**
- if the command line option is a flag (like `verbose`, not expecting a value, as you just saying you want verbose by using the flag), in the YAML it's converted to a bool (valid values are 0/1, false/true, no/yes).
- if the command line option is "multiple" (can be given multiple times), in the YAML file we will support either it being a value, or a list of values

**Comment by chipaca** [comment]
This one woke me from my sleep, so it might be completely insane, but
```yaml
build:
    requirements:
        - reqs-legacy.txt
        - reqs-new.txt
install:
    snap:
        - crossbar
        - etc
    apt:
        - postgresql
        - etc etc
# etc
```
