### ISSUE TITLE
Charm deployment to OSM fails

### ISSUE THREAD

**Issue by fotisolgr** [canonical/charmcraft#529]
Hello,

I am trying to deploy the powerDNS CNF to OSM and fails by giving me the following error: 

`error":"cannot upload charm: cannot read charm archive: invalid charm archive: ambiguous root  directory","error-code":"bad request`.

I am using charmcraft version 1.2.1 and I was able to deploy the same charm in charmcraft version 1.1.1 .

The **bundle.yaml** I am using is the following one:

```
description: PowerDNS Bundle
bundle: kubernetes
series: kubernetes
applications:
  powerdns:
    charm: ./charms/powerdns-operator
    scale: 1
  mariadb-k8s:
    charm: cs:~charmed-osm/mariadb-k8s
    scale: 1
    options:
      user: youruser
      password: yourpass
      database: yourdatabase
      root_password: yourootpassword
      mysql_port: "3306"

relations:
- - mariadb-k8s:mysql
  - powerdns:db
```

And the **metadata.yaml** is the following one:

```name: powerdns
description: |
  Kubernetes operator for PowerDNS
summary: |
  PowerDNS is a DNS server program, written in C++ and licensed under the GPL.
  It runs on most Unix derivatives. PowerDNS features a large number of different
  backends ranging from simple BIND style zonefiles to relational databases and
  load balancing/failover algorithms.

series:
  - kubernetes

deployment:
  type: stateless
  service: loadbalancer

requires:
  db:
    interface: mysql
    limit: 1
```

Any ideas on how to fix that issue would be appreciated.

Thanks in advance,
Fotis
