### ISSUE TITLE
`charmcraft pack` runs indefinitely when using parts

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charmcraft#552]
Intermittently when doing `charmcraft pack` I am hitting a `pack` that will run indefinitely. This has happened when using a 'charmcraft.yaml' file that includes:

```
parts:
  kubectl:
    plugin: dump
    source: .
    override-pull: |
      curl -sSLO https://dl.k8s.io/release/v1.22.1/bin/linux/amd64/kubectl
      chmod +x kubectl
    build-packages:
      - curl
```

Where the logs show I'm stuck on:
```
2021-09-21 15:19:53,069  craft_parts.executor.executor            DEBUG    execute action charm:Action(part_name='charm', step=Step.PULL, action_type=ActionType.UPDATE, reason='source changed').
```

I cannot consistently reproduce this, but when it does happen it will continually happen (kill+rerun `charmcraft pack` yields the same result).  Deleting the `./build` directory seems to fix the issue and the next pack will work fine.  

When this error does occur, a few lines above the stuck action I see:
```
2021-09-21 15:26:54,885  craft_parts.sources.local_source         DEBUG    ignore patterns: ['*.charm', 'build', '*.charm' ...] 
```
where the `...` has **many** repeats of "'*.charm', 'build'" (enough to fill my terminal history).  

Something similar can be reproduced by using the above `charmcraft.yaml` snippet to `pack` the `charmcraft init` template twice in a row.  The first `charmcraft pack` will show a small entry for ignore patterns, with the second `pack` showing something like:
```
2021-09-22 18:34:08,551  craft_parts.sources.local_source         DEBUG    ignore patterns: ['*.charm', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', '*.charm', 'build', 'build', 'build', 'build']
```
