### ISSUE TITLE
Please allow for installing Python dependencies from requirements files using wheels

### ISSUE THREAD

**Issue by Vultaire** [canonical/charmcraft#712]
At present, packages from requirements files are installed via pip using the ```--no-binary :all:``` flag.

This can result in exceptionally long build times which, if the charm author is OK with using pre-built wheels, are unnecessarily long.

I'm working on a charm, and its requirements.txt looks like this:

```
charmhelpers
ops
click
fabric
python-openstackclient
```

Building the venv for the above requirements takes under 30 seconds on my machine.  (Tested via both Focal and Bionic LXDs, using ```time { python3 -m venv venv; . venv/bin/activate; pip install --upgrade setuptools pip; pip install --upgrade -r requirements.txt; }```.)

I would expect charmcraft.yaml to look something like this:

```
type: "charm"
bases:
  - name: "ubuntu"
    channel: "20.04"
    architectures:
      - amd64
  - name: "ubuntu"
    channel: "18.04"
    architectures:
      - amd64
parts:
  charm:
    charm-binary-python-packages:
      # Updated versions needed for working nicely with
      # jinja2/markupsafe
      - setuptools
      - pip
```

However, the packages in the requirements.txt depend on a wide range of other packages, and with the ```--no-binary :all:``` flag, it takes a very long time - longer than I want to clock for this bug.

As an attempt at working around this issue, I've customized my charmcraft.yaml to look like this instead:

```
parts:
  charm:
    build-packages:
      # Needed by cryptography
      - libffi-dev
      - rustc
      - cargo
      - libssl-dev
    charm-binary-python-packages:
      # Updated versions needed for working nicely with
      # jinja2/markupsafe
      - setuptools
      - pip

      # Needed as prerequisites for other required packages.
      # Explicitly included here to avoid doing source-based builds
      # which take time and require installing extra dev packages.
      - setuptools-rust
      #- cryptography   # note: seems to require a source build on Bionic,
                        # which in turn requires setuptools-rust to be installed
                        # before attempting to install this.
      - bcrypt
      - pynacl          # note: no binary on bionic, but this does help focal

      # Include any of the requirements.txt packages which have wheels
      #- charmhelpers   # currently tarball-only
      - ops
      - click
      #- fabric         # currently tarball-only
      #- python-openstackclient  # pulls cryptography dependency before
                                 # setuptools-rust can be installed
```

While this does install a few more bits via binaries when possible, my Bionic build time from venv creation through final dependency install (and excluding the other parts of the charm building process) takes roughly 13.5 minutes.  Again, doing this via a normal venv only takes me roughly 30 seconds since most of the packages can be installed via wheels.

Long story short: I don't see a good workaround at present to get reasonable build times for my particular required packages when using Charmcraft 1.4.0.  Can we add an option so we can omit the ```--no-binary :all:``` when installing from requirements.txt files, or something similar in nature?

Test environment:
Host: Ubuntu 20.04
Charmcraft: latest/stable (1.4.0)
Invoked via: ```charmcraft -v pack```
Building from bases: 20.04 and 18.04
