### ISSUE TITLE
Upload resources on charmcraft upload when specified as upstream-resource in the metadata file

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/charmcraft#839]
Resources source can be specified in the metadata.yaml as `upsteam-source` but they still need to be published by running the `charmcraft upload-resource` command.

Here's a snippet of a resource with with this specified:
```
resources:
  nginx-prometheus-exporter-image:
    type: oci-image
    description: Prometheus exporter for nginx
    auto-fetch: true
    upstream-source: nginx/nginx-prometheus-exporter:0.10.0
```

Under this scenario, the resource and the charm share their life-cycle, so it would make sense to be able to publish both the charm and the resource by running the `charmcraft upload`command. This would improve developer experience and could help control dangling images when the charm upload fails after a successful resource upload, a common scenario when publishing via CI.

Thank you!
