### ISSUE TITLE
pack command succeeds without copying charm

### ISSUE THREAD

**Issue by jdkandersson** [canonical/charmcraft#879]
Potentially related to #878 

I'm working on a reactive charm. Recently, the `charmcraft pack` command has stopped working. This is the `charmcraft.yaml` file:

```yaml
type: "charm"
bases:
    - build-on:
      - name: "ubuntu"
        channel: "20.04"
      run-on:
      - name: "ubuntu"
        channel: "16.04"
      - name: "ubuntu"
        channel: "18.04"
      - name: "ubuntu"
        channel: "20.04"
parts:
  charm:
    source: .
    plugin: reactive
    build-snaps: [charm]
    build-packages:
      - virtualenv
      - git
```

This is the `metadata.yaml` file:

```yaml
name: jenkins
display-name: Jenkins
docs: https://discourse.charmhub.io/t/jenkins-docs-index/4831
summary: Jenkins Continuous Integration Server
maintainers:
  - IS SRE <launchpad.net/~canonical-is-sre>
description: >
  Jenkins is an extendable open source continuous integration server that
  monitors executions of repeated jobs. The focus of Jenkins is the
  building/testing of software project continuously, and monitoring executions
  of externally-run jobs. More information at http://jenkins-ci.org/.

  This charm provides the Jenkins master service, and when paired with the
  jenkins-slave charm provides an easy way to deploy Jenkins on Ubuntu server,
  and scale out Jenkins slaves.
tags:
  - application_development
  - ops
subordinate: false
series:
  - xenial
  - bionic
  - focal
provides:
  website:
    interface: http
  extension:
    interface: jenkins-extension
    scope: container
    optional: true
  nrpe-external-master:
    interface: nrpe-external-master
    scope: container
requires:
  master:
    interface: jenkins-slave
    optional: true
  zuul:
    interface: zuul
    optional: true
storage:
  jenkins:
    type: filesystem
    description: Jenkins data.
    location: /srv/mnt/jenkins
```

This is the log of the build where it seems that the installation of `Jinja2` fails because `markupsafe` is not installed: https://pastebin.canonical.com/p/xgKbsnvrwN/
