### ISSUE TITLE
Building with charm version 3.x does not install on bionic (Python >=3.7 is required, 3.6.9 is present)

### ISSUE THREAD

**Issue by esunar** [canonical/charmcraft#888]
When we pack with charm 3.x does not install on bionic

[Running functional tests with 3.x:](https://pastebin.ubuntu.com/p/ZyKf6V2hFg/)
```
type: charm
parts:
  charm:
    source: src
    plugin: reactive
    build-snaps: 
      - charm
bases:
    - build-on:
        - name: ubuntu
          channel: "22.04"
          architectures: ["amd64"]
      run-on:
        - name: ubuntu
          channel: "22.04"
          architectures:
              - amd64
        - name: ubuntu
          channel: "20.04"
          architectures:
              - amd64
        - name: ubuntu
          channel: "18.04"
          architectures:
              - amd64

```
[Running functional tests with 2.x:](https://pastebin.ubuntu.com/p/6nJVMzJZDN/)

```
type: charm
parts:
  charm:
    source: src
    plugin: reactive
    build-snaps: 
      - charm/2.x/stable
bases:
    - build-on:
        - name: ubuntu
          channel: "22.04"
          architectures: ["amd64"]
      run-on:
        - name: ubuntu
          channel: "22.04"
          architectures:
              - amd64
        - name: ubuntu
          channel: "20.04"
          architectures:
              - amd64
        - name: ubuntu
          channel: "18.04"
          architectures:
              - amd64

```

created a demo branch for easy tesing:

```
git clone -b charmcraft-bionic-bug https://git.launchpad.net/~esunar/charm-graylog
make charm3 #fails
make charm2 #sucess
```
