### ISSUE TITLE
`metadata.yaml` for libraries?

### ISSUE THREAD

**Issue by sed-i** [canonical/charmcraft#918]
Relations are becoming increasingly important, sometimes as important as charms.

Introducing a `metadata.yaml` file dedicated for relations could accomodate that new understanding.

For example, when a lib (e.g. `prometheus_scrape`) depends on 3rd-party code (e.g. `jinja2`), we currently document something along these lines:

```
1. charmcraft fetch-lib lib_of_interest
2. charmcraft fetch-lib dependency
3. cat "jinja2" >> requirements.txt
```

The above may change as the charmlib matures, which would have negative impact on dev exp.

It would be handy if there was a way to provide "post-fetch" instructions, for example:

```yaml
source: https://github.com/canonical/prometheus-k8s-operator/blob/main/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
docs: https://discourse.charmhub.io/t/prometheus-k8s-relations/5862

resources:
  jinja2:
    upstream-source: https://github.com/pallets/jinja/
  juju_topology:
    upstream-source: https://charmhub.io/observability-libs/libraries/juju_topology
```

Or, if we augment the fetch-lib command we could `charmcraft fetch-lib charms.[...].prometheus_scrape provider` with

```yaml
provider:
  prime:
    - MetricsEndpointProvider.py
    - common.py
  schema: https://github.com/canonical/charm-relation-interfaces/blob/main/interfaces/prometheus_scrape/v0/schemas/provider.json
requirer:
  prime:
    - MetricsEndpointRequirer.py
    - common.py
  schema: https://github.com/canonical/charm-relation-interfaces/blob/main/interfaces/prometheus_scrape/v0/schemas/requirer.json
```
