### ISSUE TITLE
Allow `charmcraft pack` override build series upon command line parameters

### ISSUE THREAD

**Issue by paulomach** [canonical/charmcraft#936]
## Proposal

Add `--build-on` and `--run-on` command line parameters to `charmcraft pack` that would override these parameters from `charmcraft.yaml` file.

## Use case

This can potentially decrease setup times on charm CI when testing for a specific series, but the charm support more than one series, e.g., `charmcraft.yaml` is:

```yaml
bases:
  - build-on:
      - name: "ubuntu"
        channel: "20.04"
    run-on:
      - name: "ubuntu"
        channel: "20.04"
  - build-on:
      - name: "ubuntu"
        channel: "22.04"
    run-on:
      - name: "ubuntu"
        channel: "22.04"
```

But CI test will matrix run only on jammy, passing the proposed arguments would avoid building the charm for focal, saving some time of the process, e.g.:

```shell
$ charmcraft pack --build-on=ubuntu:22.04 --run-on=ubuntu:22.04
```
